// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://fwwqduljnrsbsidxejqa.supabase.co";
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ3d3FkdWxqbnJzYnNpZHhlanFhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE1NzEzMjUsImV4cCI6MjA3NzE0NzMyNX0.CA1GhsWBXII9BeNbt_8fyI8rPmh7pejl5XT8KD7zxyA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce'
  }
});

// Handle invalid refresh tokens by clearing storage
supabase.auth.onAuthStateChange((event, session) => {
  if (event === 'TOKEN_REFRESHED') {
    console.log('Token refreshed successfully');
  } else if (event === 'SIGNED_OUT') {
    // Clear any stale data
    localStorage.removeItem('supabase.auth.token');
  }
});

// Check for invalid tokens on load and clear them
supabase.auth.getSession().catch((error) => {
  if (error.message?.includes('Invalid Refresh Token') || error.message?.includes('Refresh Token Not Found')) {
    console.warn('Invalid refresh token detected, clearing auth storage');
    supabase.auth.signOut();
  }
});